
version: "2.1"
services:
  fledge:
    image: robraesemann/fledge:latest
    container_name: fledge
    environment:
      - FLEDGE_ROOT=/usr/local/fledge
    volumes:
      - fledge:/usr/local/fledge
     ports:
      - 8081:8081 # Fledge API
      - 1995:1995 # Fledge API HTTPS
      - 8080:8080 # Code Server
      - 6683:6683 # HTTP South Plugin
      - 4840:4840 # OPC UA North Plugin
    restart: unless-stopped
  fledge-gui:
    image: robraesemann/fledge-gui:latest
    container_name: fledge-gui
    ports:
     - 8000:80
 